services:

  postgres:
    image: postgres:18
    container_name: cdc-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    command:
      - postgres
      - -c
      - wal_level=logical
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cdc-network

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.2.3
    container_name: cdc-redpanda
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda:9092,external://localhost:19092
      - --mode
      - dev-container
      - --smp
      - "1"
    ports:
      - "19092:19092"
      - "9644:9644"
    networks:
      - cdc-network

  console:
    image: docker.redpanda.com/redpandadata/console:v3.12.0
    container_name: cdc-console
    environment:
      KAFKA_BROKERS: redpanda:9092
    ports:
      - "8080:8080"
    depends_on:
      - redpanda
    networks:
      - cdc-network

  debezium:
    image: quay.io/debezium/connect:3.6
    container_name: cdc-debezium
    environment:
      BOOTSTRAP_SERVERS: redpanda:9092
      GROUP_ID: "1"

      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

      CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      STATUS_STORAGE_REPLICATION_FACTOR: "1"

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - redpanda
    networks:
      - cdc-network

volumes:
  postgres_data:

networks:
  cdc-network:
